#!/usr/bin/env sh
rm -f "./Basement"
rm -f "./BasementGHT.idd"
rm -f "./convertESOMTR"
rm -f "./EnergyPlus"
rm -f "./energyplus"
rm -f "./Energy+.idd"
rm -f "./Energy+.schema.epJSON"
rm -f "./EP-Compare"
rm -f "./EPMacro"
rm -f "./ExpandObjects"
rm -f "./HVAC-Diagram"
rm -f "./IDFVersionUpdater"
rm -f "./ParametricPreprocessor"
rm -f "./parser"
rm -f "./ReadVarsESO"
rm -f "./runenergyplus"
rm -f "./runepmacro"
rm -f "./runreadvars"
rm -f "./Slab"
rm -f "./SlabGHT.idd"
rm -f /usr/local/share/man/man1/energyplus.1
echo "Symbolic links to this installation of EnergyPlus have been removed."
echo "You may remove the EnergyPlus directory to completely uninstall the software."
